spring:
  application:
    name: bcheck-api
  profiles:
    active: local
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /app
    encoding:
      charset: UTF-8
      enabled: true
  port: 9090

# JWT
jwt:
  secret: aHNvbi1iY2hlY2stYXBpLXNwcmluZw==
  access-expired: 1800 # 30(분) - 단위 (초)

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bcheckdb
    username: testuser
    password: test123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
