spring:
  application:
    name: bcheck-api
  profiles:
    active: local
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /app
    encoding:
      charset: UTF-8
      enabled: true
  port: 9090

---
spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:~/test;
    driverClassName: org.h2.Driver
    username: sa
    password: test123

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
